[package]
name = "ult_algo"
version = "0.1.0"
authors = ["Victor Huberta <victorhuberta@gmail.com>"]

[dependencies]
bit-vec = "0.4.4"
num-traits = "0.2"
rand = "0.4"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false
